# Generated by Django 4.0.2 on 2022-03-20 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_comm_options_comm_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentsTabl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(verbose_name='Text of comment')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comm',
            name='avtor',
        ),
        migrations.DeleteModel(
            name='register',
        ),
        migrations.DeleteModel(
            name='comm',
        ),
    ]
