# Generated by Django 4.0.2 on 2022-03-25 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_commentstabl_remove_comm_avtor_delete_register_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentstabl',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='commentstabl',
            name='Text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='commentstabl',
            name='avtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='avtor'),
        ),
        migrations.AlterField(
            model_name='commentstabl',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
